server:
  port: 4000
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    username: root
    password: Thina
    url: jdbc:mysql://localhost:3306/regschema
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
base:
  url: "http://localhost:8080"
