server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/regschema
    username: root
    password: Surya@Sql231
    driver-class-name: com.mysql.cj.jdbc.Driver
  jdbc:
    initialize-schema: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

