server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/regschema
    username: root
    password: Surya@Sql231
    driver-class-name: com.mysql.cj.jdbc.Driver
  jdbc:
    initialize-schema: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: startup.work.231@gmail.com
    password: sbza cbcd hrxr jlfx
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
