
server:
  port: 4000
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/regschema
    username: root
    password: Thina9677@

  jdbc:
    initialize-schema: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
